### ISSUE TITLE
Error on open

### ISSUE THREAD

**Issue by macMikey** [mesopelagique/VSThemeConverter#4]
I just tried this in v19 (I assume it's supposed to be run in v19 not 18)
<img width="640" alt="Screen Shot 2021-05-25 at 09 31 37" src="https://user-images.githubusercontent.com/10867016/119508407-bad35980-bd3d-11eb-8fcb-6a592af616b9.png">
<img width="1461" alt="Screen Shot 2021-05-25 at 09 37 15" src="https://user-images.githubusercontent.com/10867016/119508411-bb6bf000-bd3d-11eb-9327-809053930c56.png">

**Comment by mesopelagique** [comment]
thanks for the report
I fix the issue I expect

(and yes its v19 beta )
