### ISSUE TITLE
[suggestion] add .gitignore

### ISSUE THREAD

**Issue by macMikey** [mesopelagique/VSThemeConverter#5]
Data
Resources/all
*.journal
*.4DD
userPreferences.*
Project/DerivedData/

**Comment by mesopelagique** [comment]
you could directly edit the file and propose as Pull Request a change , I have made the change by the way

I have some global git ignore that's why I did not add it

**Comment by macMikey** [comment]
I was going to do a PR, originally, but I didn't want to issue a PR to your master branch since most of us throw a hairball when someone does it to us.

**Comment by macMikey** [comment]
I also see that your repo does not allow PR's to master. You might want to add a develop branch
Also, you might want to add *.Match to your .gitignore.

**Comment by mesopelagique** [comment]
you could master/main to PR (I could merge on other branch and test, or even test your PR code locally before merging)

It's not a production component, it's just for fun
